
Sources/WSBlastNS.nsmap: Sources/mrsws-blast.h
	soapcpp2 -d Sources -q WSBlastNS -n -S -L -p WSBlastNS -x Sources/mrsws-blast.h

Sources/WSAdminNS.nsmap: Sources/mrsws-admin.h
	soapcpp2 -d Sources -q WSAdminNS -n -S -L -p WSAdminNS -x Sources/mrsws-admin.h

Sources/WSClustalNS.nsmap: Sources/mrsws-clustal.h
	soapcpp2 -d Sources -q WSClustalNS -n -S -L -p WSClustalNS -x Sources/mrsws-clustal.h

Sources/WSSearchNS.nsmap: Sources/mrsws-search.h
	soapcpp2 -d Sources -q WSSearchNS -n -S -L -p WSSearchNS -x Sources/mrsws-search.h


