# general makefile

all:
	$(MAKE) -Cplugin all
	$(MAKE) -Cws/blast all
	$(MAKE) -Cws/regular all
	$(MAKE) -Cws/clustal all

install:
	$(MAKE) -Cplugin install
	$(MAKE) -Cws/blast install
	$(MAKE) -Cws/regular install
	$(MAKE) -Cws/clustal install

