#!/bin/bash
#
# mrsws        Startup script for the MRS web service
#
# description: MRS Web Service regular search
# processname: mrsws
# chkconfig: - 86 14
# config: /etc/sysconfig/mrsws-search
# pidfile: /var/run/mrsws-search.pid

# Source function library.
. /etc/rc.d/init.d/functions

if [ -f /etc/sysconfig/mrsws-search ]; then
        . /etc/sysconfig/mrsws-search
fi

prog=mrsws-search
mrsws=/usr/scratch/mrs/ws/regular/mrsws
pidfile=${PIDFILE-/var/run/mrsws-search.pid}
RETVAL=0

start() {
        echo -n $"Starting $prog: "
        daemon $mrsws
        RETVAL=$?
        echo
        return $RETVAL
}
stop() {
	echo -n $"Stopping $prog: "
	killproc $mrsws
	RETVAL=$?
	echo
}
reload() {
    echo -n $"Reloading $prog: "
    killproc $prog -HUP
    RETVAL=$?
    echo
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
        status $mrsws
	RETVAL=$?
	;;
  restart)
	stop
	start
	;;
  condrestart)
	if [ -f ${pidfile} ] ; then
		stop
		start
	fi
	;;
  reload)
        reload
	;;
  graceful|help|configtest|fullstatus)
	$apachectl $@
	RETVAL=$?
	;;
  *)
	echo $"Usage: $prog {start|stop|restart|condrestart|reload|status|fullstatus|graceful|help|configtest}"
	exit 1
esac

exit $RETVAL
