# This file was automatically generated by SWIG
package SeqFilter;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package SeqFilterc;
bootstrap SeqFilter;
package SeqFilter;
@EXPORT = qw( );

# ---------- BASE METHODS -------------

package SeqFilter;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package SeqFilter;

*DUST = *SeqFilterc::DUST;
*SEG = *SeqFilterc::SEG;

# ------- VARIABLE STUBS --------

package SeqFilter;

1;
